API_PORT: 1993
LOG_TIMESTAMP: true
LOG_LEVEL: debug
ADMIN_EMAIL: foo@bar.com
DB_CONFIG:
    # Only DB_CONFIG keys are lowercase
    host: localhost
    port: 5432
    user: karr
    password: password
    db_name: karr
